# Generated by Django 5.2.1 on 2025-05-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_abstract_picture_portret_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorites_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название картины')),
                ('price', models.IntegerField(default=0)),
                ('picture', models.CharField(max_length=255, verbose_name='Путь к изображению')),
            ],
        ),
    ]
