# Generated by Django 5.2.1 on 2025-05-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_favorites_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites_picture',
            name='picture',
            field=models.ImageField(upload_to='favorites/'),
        ),
        migrations.AlterField(
            model_name='favorites_picture',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='favorites_picture',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
