# Generated by Django 5.2.1 on 2025-05-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_favorites_picture_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites_picture',
            name='original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
