# Generated by Django 5.2.1 on 2025-05-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_favorites_picture_original_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites_picture',
            name='original_id',
            field=models.IntegerField(default=0),
        ),
    ]
