# Generated by Django 5.2.1 on 2025-05-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_favorites_picture_original_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites_picture',
            name='picture_type',
            field=models.CharField(choices=[('modern', 'Современное'), ('classic', 'Классическое'), ('abstract', 'Абстрактное'), ('portret', 'Портрет')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favorites_picture',
            unique_together={('original_id', 'picture_type')},
        ),
    ]
