# Generated by Django 5.2.1 on 2025-05-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_favorites_picture_picture_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites_picture',
            name='original_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='favorites_picture',
            name='picture_type',
            field=models.CharField(max_length=10),
        ),
    ]
